setwd("T:/Teaching/STA 4504/R output")
#Sweave("c1.Rnw")
#Sweave("partyaffil_u.Rnw")
#Sweave("tea.Rnw")
#Sweave("malformation.Rnw")
Sweave("wafers.Rnw")
#Sweave("homicide.Rnw")
#Sweave("trains.Rnw")
#Sweave("FL_death.Rnw")
#Sweave("crab_msel.Rnw")
#Sweave("crossover_gee.Rnw")
#Sweave("depression2.Rnw")
#Sweave("afterlife.Rnw")
#Sweave("admissions_loglinear.Rnw")
Sweave("pol_ideo.Rnw")
